services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    command: mongod --replSet rs0 --bind_ip_all --noauth
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mongo-network

  init-mongo:
    image: mongo
    container_name: init-mongo
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        sleep 5

        if mongosh --host mongo --quiet --eval \"rs.status()\" 2>&1 | grep -q \"no replset config\"; then
          echo \"Initializing replica set...\"
          mongosh --host mongo --eval \"rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongo:27017' }]
          })\"
          echo \"Replica set initialized.\"
        else
          echo \"Replica set already initialized.\"
        fi
        "
    restart: "no"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
